name: silvimetric
channels:
  - conda-forge
dependencies:
  - python=3.11
  - tiledb-py
  - python-pdal
  - numpy
  - shapely
  - dask
  - pyproj
  - gdal
  - scipy
  - awscli=2.13.33
  - websocket-client
  - python-json-logger
  - pip:
    - line-profiler
